"""Direct appendix plots from frozen v58 results; no model runs or new tests.

Run from the counting workspace:
  python figures/synthetic_appendix_aurora/build_figures.py
"""
from pathlib import Path
import hashlib
import html
import json
import re
import shutil
import textwrap

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.lines import Line2D
from matplotlib.ticker import FuncFormatter, MaxNLocator
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw, ImageFont

OUT = Path(__file__).resolve().parent
WORK = OUT.parent.parent
DATA = WORK / 'synthetic/work/v58_final'
ALIGN = DATA / 'analysis/v58_alignment_supplement_20260905'
LEGACY = DATA / 'analysis/v58_unified_legacy_20260905'
EXTRA = DATA / 'analysis/v58_unified_additional_20260905'
PAPER = WORK / 'runs/paper_figures/figures/synthetic_appendix'
MODES = ['nonthinking', 'thinking']
NAMES = {'nonthinking': 'Non-thinking', 'thinking': 'Thinking'}
# Exact mode colors and warm heatmap anchors from the body synthetic figure.
COLORS = {'nonthinking': '#B52F6B', 'thinking': '#007EAB'}
VIOLET, ORANGE, GRAY, INK = '#6750E8', '#C77939', '#8190A5', '#161923'
WARM_STOPS = ['#161923', '#40204F', '#963878', '#E65D91', '#F7A35C', '#F9EDAD']
WARM = LinearSegmentedColormap.from_list('Aurora warm', WARM_STOPS)
COUNT_STOPS = ['#23165C', '#6750E8', '#00C2FF', '#39E58C', '#F6E36A']
COUNT = LinearSegmentedColormap.from_list('Aurora counts', COUNT_STOPS)
SOURCES, FIGURES, CHECKS = {}, [], []
TABLES = OUT / 'plot_data'
COLLECTION = 'synthetic_appendix_aurora_compact_20260908.pdf'
LAYOUT_CHECKS = []


from paper_layout import style_figure as paper_layout


def layout_audit(fig, stem):
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    from matplotlib.text import Text
    texts = [t for t in fig.findobj(Text) if t.get_visible() and t.get_text() and t.get_window_extent(renderer).width>0]
    bounds = fig.bbox
    clipped = []
    for t in texts:
        b = t.get_window_extent(renderer)
        # Ignore hidden/out-of-range tick labels generated by locators.
        if t.axes is not None and t not in t.axes.texts and t not in [t.axes.xaxis.label,t.axes.yaxis.label,t.axes._left_title]:
            continue
        if b.x0 < -1 or b.y0 < -1 or b.x1 > bounds.x1+1 or b.y1 > bounds.y1+1:
            clipped.append(t.get_text())
    LAYOUT_CHECKS.append({'figure':stem, 'width_inches':float(fig.get_figwidth()),
                          'min_font_points':min(t.get_fontsize() for t in texts),
                          'min_font_at_5_5_inches':min(t.get_fontsize() for t in texts)*5.5/fig.get_figwidth(),
                          'outside_page_text':clipped})
    if clipped:
        print('LAYOUT CHECK', stem, json.dumps(clipped,ensure_ascii=True), flush=True)


def read(path):
    path = Path(path)
    SOURCES[str(path.relative_to(WORK))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return pd.read_csv(path)


def read_json(path):
    path = Path(path)
    SOURCES[str(path.relative_to(WORK))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return json.loads(path.read_text(encoding='utf-8'))


def export(frame, name):
    frame.to_csv(TABLES / (name + '.csv'), index=False)
    return frame


def panel(ax, title, ylabel=None, percent=False):
    ax.set_title(title, loc='left', pad=10)
    if ylabel:
        ax.set_ylabel(ylabel)
    ax.grid(axis='y', color='#E8E8ED', linewidth=.65)
    ax.set_axisbelow(True)
    for side in ['top', 'right']:
        ax.spines[side].set_visible(False)
    if percent:
        ax.set_ylim(-3, 103)
        ax.set_yticks([0, 20, 40, 60, 80, 100])


def time_axis(ax, symlog=False):
    ax.axvline(1500, color=GRAY, linestyle=':', linewidth=1)
    ax.set_xlabel('Training step')
    if symlog:
        ax.set_xscale('symlog', linthresh=200, linscale=.65)
        ticks = [0, 200, 1000, 10000]
    else:
        ticks = [0, 2500, 5000, 7500, 10000]
    ax.set_xticks(ticks)
    ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f'{x/1000:g}k' if x >= 1000 else f'{x:g}'))
    ax.set_xlim(0, 10000)


def canvas(rows=1, cols=2, size=None):
    fig, axes = plt.subplots(rows, cols, figsize=size or (5.2*cols, 3.8*rows+.7), squeeze=False)
    fig.subplots_adjust(left=.075, right=.985, top=.90, bottom=.18 if rows == 1 else .11, wspace=.30, hspace=.40)
    return fig, axes


def save(fig, stem, title, caption, note, pdf):
    paper_layout(fig, stem)
    layout_audit(fig, stem)
    caption = caption.replace('Panels (a,b)', 'Panels A and B').replace('Panel (c)', 'Panel C')
    note = note.replace('Panels (a,b)', 'Panels A and B').replace('Panel (c)', 'Panel C')
    for suffix in ['pdf', 'svg', 'png']:
        fig.savefig(OUT / f'{stem}.{suffix}', dpi=300, facecolor='white', bbox_inches='tight', pad_inches=.055)
    pdf.savefig(fig, dpi=300, facecolor='white', bbox_inches='tight', pad_inches=.055)
    shutil.copy2(OUT / f'{stem}.pdf', PAPER / f'{stem}.pdf')
    FIGURES.append(dict(stem=stem, title=title, caption=caption, note=note))
    plt.close(fig)
    print('Saved', stem, flush=True)


def validate_panel(frame, groups, expected, key='key'):
    for group, f in frame.groupby(groups, dropna=False):
        assert len(f) == len(expected) and set(f[key]) == expected, (groups, group, len(f))
    CHECKS.append({'groups': groups, 'rows': len(frame), 'inputs_per_condition': len(expected), 'aligned': True})


def training_behavior(ablation, pdf):
    loss = read(DATA/'tables/eval_loss_curves.csv')
    loss = loss.loc[loss.position_encoding.eq('rope') & loss.suite.eq('task')]
    export(loss, '01_evaluation_loss')
    clean = ablation.loc[ablation.arm.eq('clean')]
    behavior = export(clean.groupby(['mode', 'count']).agg(accuracy=('ar_accuracy', 'mean'), inputs=('key', 'nunique')).reset_index(), '01_behavior_by_count')
    assert set(behavior.inputs) == {10}
    fig, aa = canvas(cols=3, size=(13.5, 4.5))
    for i, mode in enumerate(MODES):
        ax = aa[0, i]
        for source, label, style in [('train', 'Training-region evaluation', '-'), ('heldout', 'Validation-region evaluation', '--')]:
            f = loss.loc[loss['mode'].eq(mode) & loss.curve_source.eq(source)].sort_values('step')
            assert len(f) and not f.duplicated('step').any()
            ax.plot(f.step, f.token_weighted_cross_entropy, color=COLORS[mode], ls=style, label=label)
        panel(ax, f'({chr(97+i)}) {NAMES[mode]}: evaluation loss', 'Token cross-entropy')
        ax.legend(fontsize=8.5, loc='lower right')
        time_axis(ax)
    ax = aa[0, 2]
    for mode in MODES:
        f = behavior.loc[behavior['mode'].eq(mode)]
        ax.plot(f['count'], 100*f.accuracy, 'o-', color=COLORS[mode], label=NAMES[mode])
    panel(ax, '(c) Final-checkpoint counting', 'Free-generation accuracy (%)', True)
    ax.set(xlabel='True count', xticks=range(1, 11))
    ax.legend(loc='lower right')
    save(fig, '01_training_and_behavior', 'Training and counting behavior',
         'Full-sequence token-weighted evaluation cross-entropy on training and validation regions, using the archived evaluation curves. This is a fixed evaluation metric rather than the weighted training objective. The dotted line marks the objective change at step 1,500. The final-checkpoint accuracy panel uses ten confirmation inputs per count and mode; missing numeric answers are incorrect.',
         'Loss: archived evaluation suites. Accuracy: 100 confirmation inputs per mode (10 per count). One training run per mode.', pdf)


def retrieval_ablation(ablation, pdf):
    summary = export(ablation.groupby(['mode', 'arm', 'top_k', 'repeat']).agg(answer=('ar_accuracy', 'mean'), answered=('ar_answered', 'mean'), trace=('trace_exact', 'mean')).reset_index(), '02_retrieval_ablation')
    fig, aa = canvas(2, 2, (11.5, 8))
    specs = [('nonthinking', 'answer', 'Non-thinking: answer accuracy'), ('nonthinking', 'answered', 'Non-thinking: numeric-answer rate'), ('thinking', 'answer', 'Thinking: answer accuracy'), ('thinking', 'trace', 'Thinking: complete-trace accuracy')]
    for i, (mode, metric, title) in enumerate(specs):
        ax = aa.flat[i]
        f = summary.loc[summary['mode'].eq(mode)]
        baseline = float(f.loc[f.arm.eq('clean'), metric].iloc[0])
        selected = f.loc[f.arm.eq('selected')].groupby('top_k')[metric].mean()
        controls = f.loc[f.arm.eq('random')].groupby('top_k')[metric].mean()
        for k in [1, 2, 4]:
            vals = f.loc[f.arm.eq('random') & f.top_k.eq(k), metric].to_numpy()
            ax.scatter(np.full(len(vals), k), 100*vals, s=28, marker='x', color=GRAY, alpha=.85, zorder=4)
        ax.plot([0]+selected.index.tolist(), 100*np.r_[baseline, selected.values], 'o-', color=COLORS[mode], label='Selected retrieval heads')
        ax.plot([0]+controls.index.tolist(), 100*np.r_[baseline, controls.values], 's--', color=GRAY, label='Layer-matched controls: mean')
        panel(ax, f'({chr(97+i)}) {title}', 'Rate (%)', True)
        ax.set(xlabel='Number of ablated heads', xticks=[0, 1, 2, 4])
        ax.legend(fontsize=9, loc='upper right' if i == 0 else 'lower left')
    save(fig, '02_retrieval_ablation', 'Retrieval-head ablation',
         'Heads are selected on discovery inputs. Non-thinking ablation acts at the answer query; Thinking ablation acts at trace-separator queries, followed by free generation. Selected and control conditions reuse the same 100 confirmation inputs. Crosses show individual control sets (three for K=1/2; one for K=4). The non-thinking numeric-answer panel exposes the severe output failure under some controls.',
         'Same 100 inputs per condition. Gray crosses: individual matched controls. K=0: clean baseline.', pdf)


def roles_transport(pdf):
    factorial = read(LEGACY/'thinking/factorial_trials.csv')
    role = export(factorial.groupby('arm')[['ar_accuracy', 'trace_exact', 'trace_marker_count_accuracy']].mean().reset_index(), '03_head_functions')
    arms = ['clean', 'targeted_top2', 'successor_top1', 'successor_control_0', 'successor_control_1', 'successor_control_2', 'broad_top2', 'targeted_plus_successor', 'targeted_plus_broad']
    labels = ['Clean', 'Targeted Top-2', 'Successor L2H3', 'Successor control 1', 'Successor control 2', 'Successor control 3', 'Answer broad Top-2', 'Targeted + successor', 'Targeted + answer broad']
    role = role.set_index('arm').loc[arms]
    fig, aa = canvas(cols=3, size=(15, 5.8))
    fig.subplots_adjust(left=.15, wspace=.55, bottom=.16)
    for j, metric in enumerate(['ar_accuracy', 'trace_exact']):
        ax = aa[0, j]
        for i, arm in enumerate(arms):
            color = GRAY if 'control' in arm else VIOLET if 'successor' in arm else COLORS['thinking']
            value = float(role.loc[arm, metric])*100
            ax.plot([0, value], [i, i], color=color, alpha=.28, lw=2)
            ax.scatter(value, i, color=color, s=40, zorder=3)
            ax.text(value+1.8, i, f'{value:.0f}', va='center', fontsize=9)
        panel(ax, '(a) Final answer' if j == 0 else '(b) Complete trace')
        ax.set(yticks=range(len(arms)), yticklabels=labels if j == 0 else [], xlim=(0, 109), xlabel='Accuracy (%)')
        ax.invert_yaxis()
        ax.grid(axis='x', color='#E8E8ED')
    transport = read(LEGACY/'thinking/transport_trials.csv')
    ts = export(transport.groupby(['condition', 'top_k', 'repeat'])[['clean_margin', 'corrupt_margin', 'margin', 'restoration']].mean().reset_index(), '03_value_transport')
    ax = aa[0, 2]
    for cond, name, color, style in [('value_selected', 'Selected heads', COLORS['thinking'], '-'), ('value_control', 'Matched controls', GRAY, '--')]:
        f = ts.loc[ts.condition.eq(cond)].groupby('top_k').margin.mean()
        ax.plot(f.index, f.values, 'o'+style, color=color, label=name)
    for cond, label, color in [('clean', 'Clean', VIOLET), ('damaged', 'Damaged', ORANGE)]:
        val = float(ts.loc[ts.condition.eq(cond), 'margin'].iloc[0])
        ax.axhline(val, color=color, ls=':', label=label)
    ax.axhline(0, color=INK, lw=.6)
    panel(ax, '(c) Source-value restoration', 'Correct-minus-replacement logit margin')
    ax.set(xlabel='Number of patched heads', xticks=[1, 2, 4])
    ax.legend(fontsize=9, loc='center left')
    save(fig, '03_head_functions_and_transport', 'Head functions and content transport',
         'The factorial ablations compare targeted retrieval, successor L2H3, answer-side broad heads, and joint interventions on the same 100 free-generation inputs. Three matched successor controls are displayed separately (Succ. denotes successor). Broad refers to answer-side broad heads. The value-patching panel changes one source character and restores clean values at that source; it measures a local correct-versus-replacement logit margin, not whole-trace recovery. Control curves average three sets for K=1/2 and one set for K=4.',
         'Thinking, 100 inputs per condition. Panels (a,b): free generation. Panel (c): gold-prefix local prediction.', pdf)


def readability(pdf):
    metrics = pd.concat([read(LEGACY/m/'geometry/clean_layer_metrics.csv') for m in MODES], ignore_index=True)
    selections = pd.concat([read(LEGACY/m/'geometry/clean_selections.csv') for m in MODES], ignore_index=True)
    selected = selections.loc[selections.selector.eq('ncc_balanced_accuracy')]
    export(metrics[['endpoint', 'mode', 'layer', 'confirmation_ncc_balanced_accuracy', 'confirmation_rows']], '04_ncc_by_layer')
    export(selected, '04_ncc_discovery_selection')
    fig, aa = canvas(cols=2, size=(10.6, 4.5))
    for i, answer in enumerate([False, True]):
        ax = aa[0, i]
        for mode in MODES:
            f = metrics.loc[metrics['mode'].eq(mode) & metrics.endpoint.str.contains('answer_query').eq(answer) & metrics.layer.gt(0)].sort_values('layer')
            ax.plot(f.layer, 100*f.confirmation_ncc_balanced_accuracy, 'o-', color=COLORS[mode], label=NAMES[mode])
            chosen = selected.loc[selected['mode'].eq(mode) & selected.endpoint.str.contains('answer_query').eq(answer)].iloc[0]
            ax.scatter([chosen.selected_layer], [100*chosen.confirmation_value], marker='s', s=85, facecolors='none', edgecolors=COLORS[mode], linewidths=1.5, zorder=5)
        ax.axhline(10, color=GRAY, ls=':', label='Chance reference (10%)')
        panel(ax, '(a) Running index' if not answer else '(b) Final count', 'Balanced NCC accuracy (%)', True)
        ax.set(xlabel='Post-block layer', xticks=[1, 2, 3, 4])
        ax.legend(fontsize=9, loc='center right' if answer else 'upper left')
    save(fig, '04_count_readability', 'Count readability across layers',
         'Nearest-centroid accuracy after discovery-fitted standardization and whitened PCA16. Running-index accuracy averages the ten labels equally across 550 occurrence states; final-count accuracy uses 100 answer states. Squares identify layers selected by grouped discovery NCC cross-validation. All measurements use gold prefixes. These results measure label readability.',
         '100 confirmation inputs. Running: 550 states; final count: 100 states. Squares: discovery-selected layers.', pdf)
    return selected


def geometry(selected, pdf, shared_layer=None, stem='05_count_geometry'):
    clouds = pd.concat([read(LEGACY/m/'geometry/projection_cloud.csv') for m in MODES], ignore_index=True)
    fig, aa = canvas(2, 2, (11, 8.7))
    fig.subplots_adjust(right=.90, bottom=.11, hspace=.42, wspace=.30)
    points = []
    for row, answer in enumerate([False, True]):
        for col, mode in enumerate(MODES):
            chosen = selected.loc[selected['mode'].eq(mode) & selected.endpoint.str.contains('answer_query').eq(answer)].iloc[0]
            layer = int(chosen.selected_layer) if shared_layer is None else shared_layer
            f = clouds.loc[clouds.endpoint.eq(chosen.endpoint) & clouds.layer.eq(layer) & clouds.split.eq('confirmation')].copy()
            assert len(f) == (100 if answer else 550)
            assert f.prompt_sha256.nunique() == 100
            points.append(f)
            ax = aa[row, col]
            im = ax.scatter(f.pc1, f.pc2, c=f.occurrence, cmap=COUNT, vmin=1, vmax=10, s=12 if not answer else 20, alpha=.62, linewidths=0, rasterized=True)
            centroids = f.groupby('occurrence')[['pc1', 'pc2']].mean()
            ax.plot(centroids.pc1, centroids.pc2, color=GRAY, lw=.8, alpha=.6)
            ax.scatter(centroids.pc1, centroids.pc2, c=centroids.index, cmap=COUNT, vmin=1, vmax=10, s=50, edgecolors=INK, linewidths=.55, zorder=4)
            kind = 'Final count' if answer else 'Running index'
            panel(ax, f'({chr(97+2*row+col)}) {NAMES[mode]}: {kind}, L{layer}')
            ax.set_xlabel(f'PC1 ({100*f.pc1_variance_ratio.iloc[0]:.1f}% discovery variance)')
            ax.set_ylabel(f'PC2 ({100*f.pc2_variance_ratio.iloc[0]:.1f}%)')
            ax.set_aspect('equal', adjustable='datalim')
            ax.margins(.12)
    cax = fig.add_axes([.925, .25, .017, .47])
    fig.colorbar(im, cax=cax, ticks=range(1, 11), label='Count or running index')
    export(pd.concat(points), '05_pca_confirmation_points' if shared_layer is None else stem+'_points')
    layer_caption = ('Layers follow the NCC discovery selection, not a visual choice.' if shared_layer is None else
                     f'All four panels use the same post-block layer L{shared_layer}, including both modes and both endpoints. L2 and L4 are displayed as fixed depth comparisons.')
    save(fig, stem, 'Count-state PCA projections' if shared_layer is None else f'Count-state PCA at common layer L{shared_layer}',
         'Confirmation states projected with the archived discovery-fitted, non-whitened PCA basis. '+layer_caption+' NT and T denote non-thinking and thinking. Points are individual states; outlined points are confirmation class means, joined in count order. Running panels contain 550 states and final panels 100 states from the same 100 inputs. Each panel has its own PCA coordinate system and equal x/y unit scaling; distances are not comparable across panels. No points are omitted.',
         'Gold prefixes; discovery-fitted PCA. Large points: confirmation class means. Separate coordinate systems per panel.', pdf)
    return pd.concat(points)


def geometry_3d(points, pdf, shared_layer=None, stem='10_count_geometry_3d'):
    """Use the archived PC3; identical states, selected layers and PCA basis."""
    fig = plt.figure(figsize=(5.5, 6.6))
    variances = []
    for i, (answer, mode) in enumerate([(False,m) for m in MODES]+[(True,m) for m in MODES]):
        f = points.loc[points['mode'].eq(mode) & points.endpoint.str.contains('answer_query').eq(answer)]
        assert len(f) == (100 if answer else 550)
        ax = fig.add_subplot(2,2,i+1,projection='3d',computed_zorder=False)
        # Orthographic projection and equal coordinate units avoid perspective stretching.
        ax.set_proj_type('ortho')
        ax.view_init(elev=24, azim=-58)
        xyz = f[['pc1','pc2','pc3']].to_numpy()
        im = ax.scatter(*xyz.T, c=f.occurrence, cmap=COUNT, vmin=1,vmax=10,
                        s=5 if not answer else 10, alpha=.48, linewidths=0,
                        depthshade=False, rasterized=True, zorder=1)
        centers = f.groupby('occurrence')[['pc1','pc2','pc3']].mean()
        ax.plot(*centers.to_numpy().T, color=GRAY, lw=.7, alpha=.7,zorder=3)
        ax.scatter(*centers.to_numpy().T, c=centers.index, cmap=COUNT, vmin=1,vmax=10,
                   s=22, edgecolors=INK, linewidths=.4, depthshade=False,zorder=4)
        ranges = np.ptp(xyz, axis=0)
        pad = ranges*.08
        ax.set(xlim=(xyz[:,0].min()-pad[0],xyz[:,0].max()+pad[0]),
               ylim=(xyz[:,1].min()-pad[1],xyz[:,1].max()+pad[1]),
               zlim=(xyz[:,2].min()-pad[2],xyz[:,2].max()+pad[2]))
        ax.set_box_aspect(ranges, zoom=.90)
        ratios = [float(f[f'pc{j}_variance_ratio'].iloc[0]) for j in range(1,4)]
        for j, axis in enumerate([ax.xaxis, ax.yaxis, ax.zaxis]):
            axis.set_major_locator(MaxNLocator(2))
            axis.set_label_text(f'PC{j+1} ({100*ratios[j]:.1f}%)', fontsize=8.5)
            axis.labelpad=0
            axis.pane.fill=False
            axis._axinfo['grid']['color']=(.88,.89,.93,.55)
        kind = 'final' if answer else 'running'
        ax.set_title(f'{chr(65+i)}. {NAMES[mode]}: {kind}\nL{int(f.layer.iloc[0])}', loc='left')
        variances.append(dict(mode=mode, endpoint=f.endpoint.iloc[0], layer=int(f.layer.iloc[0]),
                              pc1=ratios[0], pc2=ratios[1], pc3=ratios[2],
                              cumulative_2d=sum(ratios[:2]),cumulative_3d=sum(ratios)))
    cax=fig.add_axes([.18,.075,.65,.016])
    fig.colorbar(im, cax=cax, orientation='horizontal', ticks=range(1,11),label='Count or running index')
    cax.tick_params(labelsize=8.5)
    cax.xaxis.label.set_fontsize(9)
    export(pd.DataFrame(variances), '10_pca_variance_2d_vs_3d' if shared_layer is None else stem+'_variance')
    percentages = ', '.join('/'.join(f'{100*v[f"pc{j}"]:.1f}' for j in range(1,4))+f'% ({chr(65+i)})' for i,v in enumerate(variances))
    layer_caption = ('discovery-selected layers' if shared_layer is None else f'common layer L{shared_layer}')
    save(fig, stem, 'Count-state PCA: 3D comparison' if shared_layer is None else f'Count-state PCA: 3D at common layer L{shared_layer}',
         'Three-dimensional views of exactly the same confirmation states and '+layer_caption+' as the corresponding 2D PCA figure. PC3 is taken from the same archived discovery-fitted, non-whitened PCA basis. All states are shown; outlined points are class means, joined in count order. The discovery variance fractions for PC1/PC2/PC3 are '+percentages+'. NT and T denote non-thinking and thinking. All panels use the same camera angle, orthographic projection, and equal coordinate units. Axes are fitted separately for each panel and cannot be compared across panels. Running panels contain 550 states and final panels 100 states from the same 100 inputs. The 2D view is retained for comparison.',
         'Same data and PCA basis as 2D; no refitting or state filtering.', pdf)


def progress(pdf):
    source = read(EXTRA/'thinking/source_next_trials.csv')
    ss = export(source.groupby(['arm', 'ordinary_control']).agg(accuracy=('next_marker_correct', 'mean'), inputs=('key', 'nunique'), nonempty=('blank_tokens', lambda x: int((x>0).sum()))).reset_index(), '06_next_marker_sources')
    fig, aa = canvas(cols=2, size=(12.6, 5.2))
    fig.subplots_adjust(left=.13, wspace=.48, bottom=.20)
    ax = aa[0, 0]
    arms = ['records', 'history', 'recent', 'except_recent', 'early_half']
    labels = ['Prompt target positions', 'All earlier trace items', 'Most recent trace item', 'Earlier items, except recent', 'First half of earlier items']
    for control, color, marker, offset, name in [(False, COLORS['thinking'], 'o', -.12, 'Source removed'), (True, GRAY, 's', .12, 'Token-budget control')]:
        f = ss.loc[ss.ordinary_control.eq(control)].set_index('arm').loc[arms]
        ax.scatter(100*f.accuracy, np.arange(len(arms))+offset, c=color, marker=marker, s=45, label=name)
    ax.axvline(96, color=VIOLET, ls=':', label='Clean (96%)')
    panel(ax, '(a) Sources for the next marker')
    ax.set(yticks=range(len(arms)), yticklabels=labels, xlim=(0, 103), xlabel='Next-marker accuracy (%)')
    ax.invert_yaxis(); ax.legend(fontsize=9, loc='lower left')
    ax.grid(axis='x', color='#E8E8ED')
    ax = aa[0, 1]
    rows = []
    metrics = ['donor_marker_adoption', 'donor_prefix_h2', 'donor_prefix_h3', 'donor_prefix_h4']
    supports = None
    for scope, color, marker, offset, name in [('item_span_w2', COLORS['thinking'], 'o', -.11, 'Full item (2 tokens)'), ('item_end_w1', VIOLET, 's', .11, 'Marker endpoint (1 token)')]:
        frame = read(LEGACY/'continuation'/scope/'rollout_contrasts.csv')
        f = frame.loc[frame.split.eq('confirmation') & frame.subset.eq('all') & frame.contrast.eq('full_donor_patch - full_norm_orthogonal_mean') & frame.metric.isin(metrics)].set_index('metric').loc[metrics]
        assert set(f.layer) == {1}
        if supports is None:
            supports = f[['pairs', 'prompts']].to_numpy()
        else:
            assert np.array_equal(supports, f[['pairs', 'prompts']].to_numpy())
        x = 100*f.effect.to_numpy()
        err = np.vstack([x-100*f.ci_low.to_numpy(), 100*f.ci_high.to_numpy()-x])
        ax.errorbar(x, np.arange(4)+offset, xerr=err, fmt=marker, color=color, capsize=3, label=name, markersize=5)
        rows.append(f.reset_index().assign(scope=scope))
    export(pd.concat(rows), '06_continuation_effects')
    labels = [f'{name}\n({int(n)} pairs, {int(p)} inputs)' for name, (n, p) in zip(['Next marker', '2-marker prefix', '3-marker prefix', '4-marker prefix'], supports)]
    ax.axvline(0, color=GRAY, lw=.8)
    panel(ax, '(b) Donor continuation after state transplant')
    ax.set(yticks=range(4), yticklabels=labels, xlabel='Donor adoption minus matched control (pp)')
    ax.set_ylim(4.4, -.5); ax.legend(fontsize=9, loc='lower left')
    ax.grid(axis='x', color='#E8E8ED')
    save(fig, '06_progress_state', 'Progress-state interventions',
         'Left: source-state removal at one fixed trace query per input, with equal-token-budget ordinary-position controls; cases with empty histories remain in the 100-input aggregate. Right: endpoint-aligned donor state transplants at discovery-selected L1, followed by greedy continuation under a fixed visible receiver prefix. Estimates are relative to the mean of three full-norm orthogonal controls. Intervals are the previously computed prompt-clustered 95% intervals; no new significance tests are run. Each continuation endpoint uses eight eligible inputs; the pair counts are 26/30/26/20 for the next/2/3/4-marker endpoints, respectively. The horizontal effect is donor adoption minus the matched control, in percentage points.',
         'Left: 100 inputs, gold prefixes. Right: eligible subset of 10 count-10 inputs; archived 95% intervals, free continuation.', pdf)


def answer_readout(trials, pdf):
    source = export(trials.loc[trials.family.eq('answer_source')].groupby(['mode', 'arm']).accuracy.mean().reset_index(), '07_answer_sources')
    donor = trials.loc[trials.family.eq('answer') & trials.arm.eq('adjacent_donor')].copy()
    donor['adoption'] = donor.predicted_count.eq(donor['count']+donor.offset).astype(float)
    ds = export(donor.groupby(['mode', 'layer']).agg(adoption=('adoption', 'mean'), pairs=('key', 'size')).reset_index(), '07_answer_state_donor')
    assert set(ds.pairs) == {180}
    vectors = pd.concat([read(EXTRA/m/'count_vector_trials.csv') for m in MODES])
    vs = export(vectors.groupby(['mode', 'arm', 'layer']).agg(adoption=('donor_count_adoption', 'mean'), shift=('directed_expected_shift', 'mean')).reset_index(), '07_count_direction')
    fig, aa = canvas(cols=3, size=(14, 5.2))
    fig.subplots_adjust(left=.13, wspace=.38, bottom=.18)
    ax = aa[0, 0]
    arms = ['clean', 'records', 'ordinary_records_budget', 'trace', 'ordinary_trace_budget']
    labels = ['Clean', 'Prompt targets removed', 'Prompt-budget control', 'Trace removed', 'Trace-budget control']
    for mode, offset, marker in [('nonthinking', -.11, 's'), ('thinking', .11, 'o')]:
        f = source.loc[source['mode'].eq(mode)].set_index('arm').loc[arms]
        ax.scatter(100*f.accuracy, np.arange(len(arms))+offset, color=COLORS[mode], marker=marker, label=NAMES[mode], s=36)
    panel(ax, '(a) Sources for the final answer')
    ax.set(yticks=range(len(arms)), yticklabels=labels, xlim=(0, 104), xlabel='Answer accuracy (%)')
    ax.invert_yaxis(); ax.legend(fontsize=9, loc='lower center'); ax.grid(axis='x', color='#E8E8ED')
    for j, data, title in [(1, ds, '(b) Complete answer-state transplant'), (2, vs, '(c) Rank-3 count-direction injection')]:
        ax = aa[0, j]
        for mode in MODES:
            f = data.loc[data['mode'].eq(mode)]
            if j == 2:
                control = f.loc[f.arm.str.startswith('orthogonal')].groupby('layer').adoption.mean()
                ax.plot(control.index, 100*control, 's--', color=COLORS[mode], alpha=.55, label=NAMES[mode]+' controls')
                f = f.loc[f.arm.eq('count_chord')]
            ax.plot(f.layer, 100*f.adoption, 'o-', color=COLORS[mode], label=NAMES[mode])
        panel(ax, title, 'Donor-count adoption (%)', True)
        ax.set(xlabel='Post-block layer', xticks=[1, 2, 3, 4])
        ax.legend(fontsize=8.5, loc='upper left')
    save(fig, '07_answer_readout', 'Final-answer readout and state interventions',
         'Source removal occurs after each model generates its own prefix up to the answer query; lengths and positions are held fixed. The trace-removal condition is an identity control for non-thinking. Full-state transplant uses 180 adjacent-count directed pairs per layer and measures donor-count adoption. Direction injection uses discovery-derived rank-3 centroid differences, with three norm-matched orthogonal directions averaged in the dashed controls. These interventions concern final-answer states and do not isolate a position-independent running counter.',
         'Source removal: 100 own-generated prefixes. State/direction interventions: 180 adjacent-count pairs per layer.', pdf)


def dynamics(pdf):
    gd = pd.concat([read(EXTRA/m/'geometry_dynamics_trials.csv') for m in MODES])
    gs = gd.groupby(['mode', 'endpoint', 'step', 'layer', 'occurrence']).ncc_correct.mean().groupby(['mode', 'endpoint', 'step', 'layer']).mean().reset_index()
    export(gs, '08_ncc_dynamics')
    for mode in MODES:
        depths = read_json(LEGACY/mode/'geometry/frozen_depths.json')
        for endpoint, f in gd.loc[gd['mode'].eq(mode)].groupby('endpoint'):
            assert set(f.layer) == {depths[endpoint]}
            for step, group in f.groupby('step'):
                assert group.prompt_sha256.nunique() == 100
                assert len(group) == (100 if 'answer_query' in endpoint else 550)
    fig, aa = canvas(2, 2, (11.5, 8))
    for i, answer in enumerate([False, True]):
        ax = aa[0, i]
        for mode in MODES:
            f = gs.loc[gs['mode'].eq(mode) & gs.endpoint.str.contains('answer_query').eq(answer)].sort_values('step')
            ax.plot(f.step, 100*f.ncc_correct, 'o-', color=COLORS[mode], label=f'{NAMES[mode]} (L{int(f.layer.iloc[0])})')
        panel(ax, '(a) Running-index readability' if not answer else '(b) Final-count readability', 'Balanced NCC accuracy (%)', True)
        ax.axhline(10, ls=':', color=GRAY); ax.legend(fontsize=9, loc='center right' if answer else 'upper right')
        time_axis(ax, True)
    causal = pd.concat([read(LEGACY/m/'dynamics_causal_trials.csv') for m in MODES])
    cs = causal.groupby(['mode', 'step', 'condition', 'repeat'])[['ar_accuracy', 'trace_exact']].mean().reset_index()
    export(cs, '08_causal_dynamics')
    ax = aa[1, 0]
    for mode in MODES:
        for metric, name, style in [('ar_accuracy', 'answer', '-'), ('trace_exact', 'trace', '--')]:
            if mode == 'nonthinking' and metric == 'trace_exact':
                continue
            f = cs.loc[cs['mode'].eq(mode)].groupby(['step', 'condition'])[metric].mean().unstack()
            ax.plot(f.index, 100*(f.control-f.selected), 'o'+style, color=COLORS[mode], label=f'{NAMES[mode]}: {name}')
    panel(ax, '(c) Extra damage from selected Top-2', 'Control minus selected accuracy (pp)')
    ax.axhline(0, color=GRAY, lw=.8); ax.legend(fontsize=9, loc='lower left'); time_axis(ax, True)
    transport = []
    for folder in sorted((LEGACY/'thinking').glob('transport_step_*')):
        transport.append(read(folder/'transport_trials.csv').assign(step=int(folder.name.rsplit('_', 1)[1])))
    ts = export(pd.concat(transport).groupby(['step', 'condition', 'top_k', 'repeat']).restoration.mean().reset_index(), '08_transport_dynamics')
    ax = aa[1, 1]
    for condition, color, style, name in [('value_selected', COLORS['thinking'], '-', 'Selected Top-2'), ('value_control', GRAY, '--', 'Matched controls')]:
        f = ts.loc[ts.condition.eq(condition) & ts.top_k.eq(2)].groupby('step').restoration.mean()
        ax.plot(f.index, f.values, 'o'+style, color=color, label=name)
    panel(ax, '(d) Targeted content transport', 'Patched minus damaged logit margin')
    ax.axhline(0, color=GRAY, lw=.8); ax.legend(fontsize=9, loc='upper left'); time_axis(ax, True)
    save(fig, '08_learning_dynamics', 'Readability and causal effects during training',
         'Eleven preselected checkpoints reuse the same confirmation inputs. NCC transformations and centroids are refitted on discovery at each checkpoint, with common-decoder-selected physical layers fixed throughout; balanced running accuracy weights labels equally. Ablation curves show control accuracy minus selected-head accuracy, including negative values. Targeted value restoration shows raw local logit-margin gains. Controls are averaged over the archived matched sets. The horizontal axis is linear through step 200 and logarithmic afterwards; step 0 is retained. The dotted vertical line marks step 1,500.',
         'Fixed 100-input panel. X axis: linear to 200, then logarithmic. Dotted vertical line: objective change at 1,500.', pdf)


def attention_roles(pdf):
    attention = pd.concat([read(LEGACY/m/'dynamics_attention_summary.csv') for m in MODES])
    export(attention, '09_attention_roles')
    fig, aa = canvas(2, 2, (12.5, 10.5))
    fig.subplots_adjust(bottom=.08, top=.94, right=.90, wspace=.36, hspace=.30)
    heads = [(l, h) for l in range(1, 5) for h in range(8)]
    broad_max = float(attention.broad.max())
    for i, (mode, role, title, label, vmax) in enumerate([
        ('nonthinking', 'broad', 'Non-thinking: answer-side broad', r'Broad score $B_h$', broad_max),
        ('thinking', 'broad', 'Thinking: answer-side broad', r'Broad score $B_h$', broad_max),
        ('thinking', 'targeted', 'Thinking: targeted retrieval', r'Targeted score $T_h$', 1),
        ('thinking', 'successor', 'Thinking: successor attention', 'Marker-to-separator attention', 1),
    ]):
        ax = aa.flat[i]
        f = attention.loc[attention['mode'].eq(mode)]
        m = f.pivot(index=['layer', 'head'], columns='step', values=role).reindex(heads)
        assert m.shape == (32, 101) and np.isfinite(m.to_numpy()).all()
        im = ax.pcolormesh(m.columns.to_numpy(), np.arange(32), m.to_numpy(), cmap=WARM, vmin=0, vmax=vmax, shading='nearest', rasterized=True)
        ax.set_title(f'({chr(97+i)}) {title}', loc='left', pad=10)
        ax.set_ylim(31.5, -.5)
        ax.set_yticks(range(32), [f'L{l}H{h}' for l, h in heads], fontsize=7)
        ax.tick_params(axis='y', length=0)
        for y in [7.5, 15.5, 23.5]:
            ax.axhline(y, color='white', lw=.6, alpha=.65)
        time_axis(ax)
        fig.colorbar(im, ax=ax, pad=.025, fraction=.04, label=label)
    save(fig, '09_retrieval_roles', 'Complete attention-role dynamics',
         'All 32 physical heads retain their order across 101 checkpoints; tick labels are shown for every second head. Scores are absolute and are not normalized across heads or checkpoints. Broad panels share one fixed scale across both modes; targeted and successor panels have fixed 0-1 scales. Broad and targeted scores use the definitions in the manuscript. Successor attention is measured from each trace marker to its immediately preceding separator. All scores are measured with gold prefixes on the fixed 100-input panel. Heatmap color intensity must be interpreted using each colorbar.',
         '100 gold-prefix inputs per checkpoint. Fixed physical heads and absolute scores. Broad panels share a color scale.', pdf)


def gallery():
    entries = []
    for f in FIGURES:
        entries.append(f'<section id="{f["stem"]}"><h2>{html.escape(f["title"])}</h2><a href="{f["stem"]}.pdf">PDF</a> · <a href="{f["stem"]}.png">PNG</a> · <a href="{f["stem"]}.svg">SVG</a><img src="{f["stem"]}.png" alt="{html.escape(f["title"])}"><p>{html.escape(f["caption"])}</p></section>')
    doc = '<!doctype html><meta charset="utf-8"><title>Synthetic appendix — Aurora</title><style>body{max-width:1200px;margin:40px auto;padding:0 24px;font:16px/1.6 system-ui;color:#161923;background:white}h1{font-size:28px}h2{font-size:21px}section{margin:45px 0;border-top:1px solid #ddd;padding-top:20px}img{display:block;width:100%;height:auto;margin-top:15px}a{color:#007EAB}p{max-width:1050px}</style><h1>Synthetic appendix: direct results in Aurora colors</h1><p>Frozen v58 results. One training run per mode. No new model runs, significance tests, or SNR/silhouette panels.</p><p><a href="'+COLLECTION+'">All figures (PDF, 2026-09-08)</a></p>'+''.join(entries)
    (OUT/'index.html').write_text(doc, encoding='utf-8')
    md = '# Synthetic appendix figures — Aurora\n\n'
    md += '[新版图合集]('+COLLECTION+') · [论文尺寸预览（含图注）](synthetic_appendix_compact_paper_review_20260908.pdf)\n\n'
    md += '正文同款模式颜色：Non-thinking `#B52F6B`，Thinking `#007EAB`。热图使用正文相同暖色渐变；PCA 使用已有 Aurora count 渐变。原始结果和正文文件未改动。\n\n'
    md += '2026-09-08 更新：按插入论文后 5.5 英寸宽度核算，坐标标签 9 pt、图例通常 8.5 pt、最小字号 8 pt；子图统一使用 A. B. C.。图 01、03、07 保持紧凑横向三栏，图 06 改为并排双栏；四宫格统一子图高度和间距。自动收紧外边距，图注统一留出 6 pt 间距。完整说明放在独立图注中。图 10 为与图 05 同数据、同层、同 PCA 基底的 3D 对照。\n\n'
    md += 'PDF 为独立矢量图（密集散点/热图栅格化）；PNG 为 300 dpi；另提供 SVG、合集 PDF 和 HTML 图册。独立 PDF 同步到 `runs/paper_figures/figures/synthetic_appendix/`。旧版本保存在 `archive/20260907/` 和 `archive/20260908_before_aspect/`。\n\n'
    tex = '% Standalone candidate figures; not automatically included in main.tex.\n'
    for f in FIGURES:
        md += f'## {f["stem"]}: {f["title"]}\n\n[PDF]({f["stem"]}.pdf) · [PNG]({f["stem"]}.png) · [SVG]({f["stem"]}.svg)\n\n{f["caption"]}\n\n'
        caption = f['caption'].replace('%', r'\%').replace('_', r'\_')
        tex += '\n\\GPT{\n\\begin{figure}[p]\n\\centering\n\\includegraphics[width=\\linewidth]{figures/synthetic_appendix/'+f['stem']+'.pdf}\n\\caption{'+caption+'}\n\\label{fig:'+f['stem'].replace('_', '-')+'}\n\\end{figure}\n}\n'
    md += '## Reproduce\n\nRun from the counting workspace:\n\n```powershell\n& "python" "figures/synthetic_appendix_aurora/build_figures.py"\n```\n\n`plot_data/` 保存全部绘图汇总；`manifest.json` 保存源数据哈希、配色和校验。图 06 的误差条直接读取已有区间；其他图为固定面板的描述性汇总。\n'
    (OUT/'README.md').write_text(md, encoding='utf-8')
    (OUT/'captions.tex').write_text(tex, encoding='utf-8')
    shutil.copy2(OUT/'captions.tex', PAPER/'captions.tex')
    # Review at the actual 5.5-inch inclusion width, with captions kept outside images.
    proof = r'''\documentclass[10pt]{article}
\usepackage[paperwidth=7.5in,paperheight=11in,textwidth=5.5in,textheight=9in]{geometry}
\usepackage{graphicx,times,caption}
\captionsetup{font=small,labelfont=bf,skip=6pt}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
'''
    for f in FIGURES:
        cap = f['caption'].replace('%',r'\%').replace('_',r'\_')
        proof += '\\begin{minipage}{\\linewidth}\n\\includegraphics[width=5.5in]{'+f['stem']+'.pdf}\n'
        proof += '\\captionof{figure}{\\textbf{'+f['title']+'.} '+cap+'}\n\\end{minipage}\n\\par\\vspace{16pt}\n'
    proof += '\\end{document}\n'
    (OUT/'compact_paper_review.tex').write_text(proof,encoding='utf-8')
    # Compact contact sheet for quickly checking completeness and palette consistency.
    width, cell_h = 1500, 530
    sheet = Image.new('RGB', (width, cell_h*((len(FIGURES)+2)//3)), 'white')
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.truetype('C:/Windows/Fonts/arial.ttf', 17)
    for i, f in enumerate(FIGURES):
        im = Image.open(OUT/(f['stem']+'.png')).convert('RGB')
        im.thumbnail((width//3-20, cell_h-55))
        x, y = (i%3)*(width//3), (i//3)*cell_h
        draw.text((x+10, y+10), textwrap.fill(f'{i+1:02d}  {f["title"]}', width=48), fill=INK, font=font)
        sheet.paste(im, (x+(width//3-im.width)//2, y+50))
    sheet.save(OUT/'overview.png')


def main():
    TABLES.mkdir(parents=True, exist_ok=True)
    PAPER.mkdir(parents=True, exist_ok=True)
    protected = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in [WORK/'runs/paper_figures/main.tex', WORK/'runs/paper_figures/appendix/synthetic.tex']}
    for root in [ALIGN, LEGACY, EXTRA]:
        assert read_json(root/'manifest.json')['status'] == 'complete'
    registry = read(ALIGN/'input_registry.csv')
    confirmation = registry.loc[registry.split.eq('confirmation')]
    expected = set(confirmation.key)
    assert len(expected) == 100 and confirmation.groupby('count').size().to_dict() == {k: 10 for k in range(1, 11)}
    ablation = pd.concat([read(ALIGN/m/'ablation.csv') for m in MODES], ignore_index=True)
    validate_panel(ablation, ['mode', 'arm', 'top_k', 'repeat'], expected)
    trials = pd.concat([read(ALIGN/m/'trials.csv') for m in MODES], ignore_index=True)
    plt.rcParams.update({'font.family': 'Times New Roman', 'font.size': 10, 'mathtext.fontset': 'stix', 'axes.titlesize': 11, 'axes.labelsize': 10, 'xtick.labelsize': 9, 'ytick.labelsize': 9, 'legend.fontsize': 9, 'legend.frameon': False, 'axes.linewidth': .6, 'lines.linewidth': 1.6, 'lines.markersize': 4, 'pdf.fonttype': 42, 'ps.fonttype': 42, 'svg.fonttype': 'none', 'text.color': INK, 'axes.labelcolor': INK, 'axes.titlecolor': INK, 'figure.facecolor': 'white'})
    with PdfPages(OUT/COLLECTION) as pdf:
        training_behavior(ablation, pdf)
        retrieval_ablation(ablation, pdf)
        roles_transport(pdf)
        selected = readability(pdf)
        points = geometry(selected, pdf)
        progress(pdf)
        answer_readout(trials, pdf)
        dynamics(pdf)
        attention_roles(pdf)
        geometry_3d(points, pdf)
        common_points={}
        for layer,stem in [(2,'11_pca_common_l2'),(4,'12_pca_common_l4')]:
            common_points[layer]=geometry(selected,pdf,shared_layer=layer,stem=stem)
        for layer,stem in [(2,'13_pca_common_l2_3d'),(4,'14_pca_common_l4_3d')]:
            geometry_3d(common_points[layer],pdf,shared_layer=layer,stem=stem)
    gallery()
    for path, before in protected.items():
        assert hashlib.sha256(path.read_bytes()).hexdigest() == before, path
    for rel, before in SOURCES.items():
        assert hashlib.sha256((WORK/rel).read_bytes()).hexdigest() == before, rel
    manifest = {'figures': FIGURES, 'source_sha256': SOURCES, 'mode_colors': COLORS, 'warm_heatmap_stops': WARM_STOPS, 'count_color_stops': COUNT_STOPS, 'palette_reference': 'figures/synthetic_training_dynamics_three-panel/plot_synthetic_section.py', 'training_runs_per_mode': 1, 'confirmation_inputs': 100, 'new_significance_tests': False, 'raw_data_unchanged': True, 'manuscript_unchanged': True, 'checks': CHECKS, 'figure_count': len(FIGURES), 'layout_checks':LAYOUT_CHECKS}
    (OUT/'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    print(json.dumps({'figure_count': len(FIGURES), 'out': str(OUT), 'paper_pdfs': str(PAPER)}, indent=2))


if __name__ == '__main__':
    main()
